apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: praveenksarathi/praveen-python:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
